<?xml version="1.0" encoding="utf-8"?><Database Name="Puzzle" Class="linqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Puzzle.mdf;Integrated Security=True" SettingsObjectName="CodePuzzle.Properties.Settings" SettingsPropertyName="PuzzleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.users" Member="users">
    <Type Name="users">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="NChar(40)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NChar(40)" CanBeNull="true" />
      <Column Name="access" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="surname" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.task_struct" Member="task_struct">
    <Type Name="task_struct">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_test" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="code_text" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="code_text2" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="handwork" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.test" Member="test">
    <Type Name="test">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Member="t_name" Storage="_name" Type="System.String" DbType="NChar(80)" CanBeNull="true" />
      <Column Name="lvl" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="language" Type="System.String" DbType="NChar(80)" CanBeNull="true" />
      <Column Name="theme" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.lib" Member="lib">
    <Type Name="lib">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="theme" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="url" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.result" Member="result">
    <Type Name="result">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_test" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="point" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[group]" Member="group" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="datatime" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
    </Type>
  </Table>
</Database>